# Generated by Django 5.0.6 on 2025-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_email_order_full_name_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='Apple', max_length=100, verbose_name='Производитель'),
        ),
    ]
